### ISSUE TITLE
Fix vagrant in puppet acceptance tests

### ISSUE THREAD

**Issue by JoshVanL** [jetstack/tarmak#546]
/bug

**What happened**:
Often the puppet acceptance tests fail due to vagrant timing out when spinnging up a machine for tests that would otherwise pass.
```
I0925 17:04:31.396]   Failed to exec 'vagrant up --provider libvirt'. Error was /root/.vagrant.d/gems/2.4.4/gems/fog-core-1.43.0/lib/fog/core/wait_for.rb:9:in `block in wait_for': The specified wait_for timeout (2 seconds) was exceeded (Fog::Errors::TimeoutError)
I0925 17:04:31.396]   	from /root/.vagrant.d/gems/2.4.4/gems/fog-core-1.43.0/lib/fog/core/wait_for.rb:6:in `loop'
I0925 17:04:31.396]   	from /root/.vagrant.d/gems/2.4.4/gems/fog-core-1.43.0/lib/fog/core/wait_for.rb:6:in `wait_for'
I0925 17:04:31.396]   	from /root/.vagrant.d/gems/2.4.4/gems/fog-core-1.43.0/lib/fog/core/model.rb:69:in `wait_for'
I0925 17:04:31.397]   	from /root/.vagrant.d/gems/2.4.4/gems/vagrant-libvirt-0.0.43/lib/vagrant-libvirt/action/wait_till_up.rb:42:in `block (2 levels) in call'
I0925 17:04:31.397]   	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/util/retryable.rb:17:in `retryable'
I0925 17:04:31.397]   	from /root/.vagrant.d/gems/2.4.4/gems/vagrant-libvirt-0.0.43/lib/vagrant-libvirt/action/wait_till_up.rb:37:in `block in call'
```

**What you expected to happen**:
Tests to not flake due to an external tool to tarmak.

**How to reproduce it (as minimally and precisely as possible)**:
`/retest` on any puppet related PR

**Comment by simonswine** [comment]
This is a really big annoiance and a good point to raise. We need to have a collection of those vagrant / libvirt related errors. Always provide a full link to the flaking test. (Make sure you use a appspot.com link, as those logs will stick around for longer).

I am currently looking into that one (https://jetstack-build-infra.appspot.com/build/jetstack-logs/pr-logs/pull/jetstack_tarmak/537/tarmak-puppet-module-tarmak-acceptance-1-9-centos/633/)

```
Failed to exec 'vagrant up --provider libvirt'. Error was Error occurred while creating new network: Call to virNetworkDefineXML failed: operation failed: network 'vagrant-libvirt' already exists with uuid 745f8dd2-3bb1-4124-9659-c816661463bd.
```

I am already working on a fix for that particular issue

@JoshVanL this is your error: https://jetstack-build-infra.appspot.com/build/jetstack-logs/pr-logs/pull/jetstack_tarmak/540/tarmak-puppet-module-tarmak-acceptance-1-10-centos/422/

We should all of those errors to that ticket and then we can see and debug each of them @MattiasGees @JoshVanL @dippynark @alljames


```

**Comment by simonswine** [comment]
There still are some problems with the ubuntu test:
- https://jetstack-build-infra.appspot.com/build/jetstack-logs/pr-logs/pull/jetstack_tarmak/570/tarmak-puppet-module-tarmak-acceptance-1-10-ubuntu/152/

Seems like the keyserver is sometimes not available
